### ISSUE TITLE
Role based authorisation based on JWT access token  

### ISSUE THREAD

**Issue by kyostiebi** [GMOD/Apollo3#136]
Implement NestJS role based authorisation based on the fact that authentication will provide JWT access token.

- There will be three hard coded roles: _admin_, _user_ and _read-only_
- The roles inherit as following:  _user_ role inherits _read-only_ role. And _admin_ inherits _user_ and _read-only_ roles.
- Each controller and endpoint may have their own role permissions
- Change controller must have an additional authorisation layer where each _changeType_ may have an own authorisation requirement. Additional authorisation roles are defined in _roles.changePermissions.ts_ where keys are possible change types and their values are _admin_, _user_ and _read-only_.
- Users and their roles will be saved in _Users_ collection where collection properties are: _ObjectId_, _id_, _username_, _email_, _roles_ and _timestamp_.
- Authorisation should be based on NestJS _Guards_ (https://docs.nestjs.com/guards)

**Comment by rbuels** [comment]
Don't forget that all authorizations are to be implemented as Validations.

**Comment by garrettjstevens** [comment]
@rbuels the Validations are used for validating changes, but this issue is more for things like "can this user upload a file to the `/files` endpoint?" or "can this user get a list of assemblies from the `/assemblies` endpoint, which are not a change-based actions. There will be additional, more complicated authorizations that deal with changes and validations.

**Comment by garrettjstevens** [comment]
From today's meeting
- Guard should be `@Validation` instead of `@Role`
- changeRegistry and ValidationSet should be added to a global module so that they can be accessed by any module
- Add interceptor to convert serialized change into change object before it's used by the ValidationGuard or a controller
- Make frontendPreValidate able to take an object '{context, reflector}' or a Change
- Add a default validation that applies the `admin`, `user`, and `read-only` logic described above
