### ISSUE TITLE
Create Artemis-style six-frame feature view

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#174]
Create a new display type that has six row, one for each frame, and shows features with each subfeature on it's associated frame row. See the Artemis screenshot below for an example. Display will also likely include sequence integration, such as the marks in the below screenshot that indicate stop codons.

![image](https://user-images.githubusercontent.com/25592344/206591656-d8aa4a40-4842-4c3a-a08e-8a146a1f7e30.png)

**Comment by haessar** [comment]
Note of a bug I encountered while testing out the existing different display types for the Reference sequence track: Attempting to choose the "GC content display" display results in a bunch of mobx-state-tree errors in the console. This happens both on the live demo and my dev server.

**Comment by cmdcolin** [comment]
just a random idea: this type of feature could be made a part of jbrowse itself, as it could benefit non-apollo users. 



also note also how apollo 1 does this (it just uses colored boxes on different CDS subfeatures instead of this six frame feature) on both the annotation track and other gene feature tracks

![Screenshot from 2022-12-13 11-35-09](https://user-images.githubusercontent.com/6511937/207416877-bf87fa55-53ff-4fbb-849f-dd9aba413103.png)


see also https://github.com/GMOD/jbrowse-components/issues/3010

would also be curious what issue you saw @haessar

**Comment by haessar** [comment]
This is the error I see both locally and in the demo when opening the "GC content display" display type in the Reference sequence track in Linear Genome View
![image](https://user-images.githubusercontent.com/11962461/207576963-658fa10b-fa0d-4846-9d6c-eeca5c47fd24.png)

**Comment by cmdcolin** [comment]
@haessar nice work on the six frame prototype :) certainly it's always a design balance, probably just making multiple optiosn available is good

i made a possible fi for the GC content display issue here https://github.com/GMOD/jbrowse-components/pull/3402 if you want to try it out
