### ISSUE TITLE
Multiple tracks to be centrally loaded

### ISSUE THREAD

**Issue by nds** [GMOD/Apollo3#214]
We have a use case where we would like to "pre-load" tracks for the users. This will be a mix of GFFs and BAMs. We would like them to appear as separate tracks, and perhaps even be configured to display in different colours etc. At the moment, the admin users can load only GFFs centrally by using "Import features"; however, all information gets collapsed into the same track. This would be such a useful feature. Thank you.

**Comment by sgiorgetti** [comment]
Thanks @garrettjstevens  - I have a couple of additional questions though.

If we pre-load some tracks by appropriately setting our `config.json`, what happens when we (admin) upload 1 more GFF via "Import Features"? I suppose they are loaded in a different track. May you confirm?

Also, if we (wicked admins) decided to import another set of features (GFF) via "Import Features" again, do these latter get collapsed into the same track?

**Comment by garrettjstevens** [comment]
Anything added via the "Import Features" menu item under the Apollo menu will get added to the Apollo track (shows up as "Annotations (<assembly name>)" in the track selector. That track will always show up when Apollo is loaded, even if it has nothing in it. If there are already features there, the imported features get added to the existing features in the Apollo track.

Any tracks added to the `config.json` will show up as separate tracks in the track selector.

**Comment by sgiorgetti** [comment]
Thanks @garrettjstevens !
