### ISSUE TITLE
Setting the status to 0 causes high latency

### ISSUE THREAD

**Issue by shashankbrgowda** [GMOD/Apollo3#436]
Setting the status to 0 for operations like AddRefSeqAliasesChange, LocationStartChange, LocationEndChange, etc., causes high latency when large assemblies are loaded into the database.

https://github.com/GMOD/Apollo3/blob/main/packages/apollo-collaboration-server/src/changes/changes.service.ts#L163-L205

**Comment by garrettjstevens** [comment]
Short-term, we should make it so that setting the status only happens after relevant changes, not all changes. I think the relevant changes are: AddAssemblyAndFeaturesFromFileChange, AddAssemblyFromExternalChange, AddAssemblyFromFileChange, and AddFeatureChange.

Long-term, we might want to see if there's a different way to do what the `status` field does. It's there to be able to easily remove entries if there is an error later on in adding the assembly/features, since those actions are often too big to use a db transaction.
